(* ::Package:: *)

(*
    ETensor.wl

    This file defines perturbative coefficients for the lowered vierbein
        (e_beta)_m
    in the symmetric vierbein gauge.

    The perturbative expansion implemented here is

        (e_beta)_m =
            Sum[
                kappa^n Binomial[1/2, n]
                (h^n)_{beta m},
                {n, 0, Infinity}
            ].

    The coefficient of order n is defined by

        ((e_beta)_m)^{rho1 sigma1 ... rhon sigman}
            =
        Binomial[1/2, n]
        eta_{beta lambda} eta_{m tau}
        I_{(1+n)}^{lambda tau rho1 sigma1 ... rhon sigman}.

    In the implementation, eta is represented by the FeynCalc metric
    MTD.  The tensor I is generated by ITensorPlain.  Therefore the
    implementation does not introduce a mixed coordinate--local-Lorentz
    Kronecker delta as a primitive object.  This is intentional: FeynCalc
    treats Lorentz indices through metric contractions, and the mixed
    background vierbein delta_beta^m is not represented as an independent
    Lorentz tensor.

    The file exports two functions:

        ETensorPlain[{beta, m}, indexArray]

    returns the ordered, non-symmetrised coefficient

        Binomial[1/2, n]
        MTD[beta, lambda] MTD[m, tau]
        ITensorPlain[{lambda, tau, rho1, sigma1, ..., rhon, sigman}],

    where indexArray = {rho1, sigma1, ..., rhon, sigman} and
    n = Length[indexArray]/2.

        ETensor[{beta, m}, indexArray]

    returns the same coefficient symmetrised with respect to the
    perturbation index pairs.  The symmetrisation is performed only over
    the indices contained in indexArray.  The external indices beta and m
    are not symmetrised, because they label the two slots of the vierbein.

    Both functions are memoised because the same tensor coefficients are
    used repeatedly during the generation of Feynman rules.
*)


SetDirectory[DirectoryName[$InputFileName]];


BeginPackage["ETensor`",{"FeynCalc`","ITensor`","indexArraySymmetrization`"}];


ETensorPlain::usage =
"ETensorPlain[{\[Beta], m}, {\!\(\*SubscriptBox[\(\[Rho]\), \(1\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(1\)]\),\[Ellipsis],\!\(\*SubscriptBox[\(\[Rho]\), \(n\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(n\)]\)}] returns the ordered perturbative \
coefficient of the lowered vierbein (e_\[Beta])_m.

The list indexArray must have the form {rho1, sigma1, ..., rhon, sigman}. \
The function interprets n = Length[indexArray]/2 and evaluates

  Binomial[1/2, n] MTD[beta, lambda] MTD[m, tau]
  ITensorPlain[{lambda, tau, rho1, sigma1, ..., rhon, sigman}].

No symmetrisation over perturbation index pairs is performed.  The external \
indices beta and m are not symmetrised.";


ETensor::usage =
"ETensor[{\[Beta], m}, {\!\(\*SubscriptBox[\(\[Rho]\), \(1\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(1\)]\),\[Ellipsis],\!\(\*SubscriptBox[\(\[Rho]\), \(n\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(n\)]\)}] returns the perturbative coefficient of the \
lowered vierbein (e_\[Beta])_m symmetrised over all perturbation index pairs.

The list indexArray must have the form {rho1, sigma1, ..., rhon, sigman}. \
The function symmetrises ETensorPlain[{\[Beta], m}, indexArray] with respect to \
permutations of the pairs {rhoi, sigmai} and flips rhoi <-> sigmai inside each \
pair.  The external indices beta and m are kept fixed and are not included in \
the symmetrisation.";


Begin["Private`"];


Clear[ETensorPlain];

ETensorPlain[indexArrayExternal : {_, _}, indexArrayInternal_List] :=
    ETensorPlain[indexArrayExternal, indexArrayInternal] =
        Module[{beta, m, lambda, tau, n},

            {beta, m} = indexArrayExternal;
            n = Length[indexArrayInternal]/2;

            lambda = Unique["lambda"];
            tau = Unique["tau"];

            Expand[
                Contract[
                    Binomial[1/2, n] *
                    MTD[beta, lambda] *
                    MTD[m, tau] *
                    ITensorPlain[
                        Join[
                            {lambda, tau},
                            indexArrayInternal
                        ]
                    ]
                ]
            ]
        ];


Clear[ETensor];

ETensor[indexArrayExternal : {_, _}, indexArrayInternal_List] :=
    ETensor[indexArrayExternal, indexArrayInternal] =
        Module[{n},

            n = Length[indexArrayInternal]/2;

            If[
                indexArrayInternal === {},

                ETensorPlain[indexArrayExternal, indexArrayInternal],

                Expand[
                    1/Power[2, n] *
                    1/Factorial[n] *
                    Total[
                        Map[
                            ETensorPlain[indexArrayExternal, #] &,
                            indexArraySymmetrization[indexArrayInternal]
                        ]
                    ]
                ]
            ]
        ];


End[];


EndPackage[];
