(* ::Package:: *)

(* ::Package:: *)


(*
    GravitonFermionVertex.wl

    This file defines the graviton-fermion interaction vertex generated
    by the perturbative expansion of the Dirac action in the vierbein
    formalism.

    The implemented action contribution is

        Sqrt[-g] (e^mu)_m
            1/2 [bar[psi] gamma^m partial_mu psi
                 - partial_mu bar[psi] gamma^m psi]

        - mass Sqrt[-g] bar[psi] psi

        - i/8 Sqrt[-g] (e^alpha)_a (e^beta)_b
            partial_alpha (e_beta)_m
            bar[psi] (gamma^a gamma^m gamma^b
                    - gamma^b gamma^m gamma^a) psi.

    After Fourier transformation, the vertex naturally splits into two
    contributions.

    The first contribution contains the fermion kinetic term and the
    fermion mass term:

        1/2 (Sqrt[-g] (e^mu)_m)^{rho1 sigma1 ... rhon sigman}
            gamma^m (p2 - p1)_mu

        - mass (Sqrt[-g])^{rho1 sigma1 ... rhon sigman}.

    This contribution is implemented by the private function

        GravitonFermionVertexKineticMassOrderedUncontracted.

    The second contribution contains the spin-connection term:

        1/8 Sum[
            (k1 + ... + ks)_alpha
            ((e_beta)_m)^{rho1 sigma1 ... rhos sigmas}
            (Sqrt[-g] (e^alpha)_a (e^beta)_b)
                ^{rho{s+1} sigma{s+1} ... rhon sigman}
            (gamma^a gamma^m gamma^b
             - gamma^b gamma^m gamma^a),
            {s, 1, n}
        ].

    This contribution is implemented by the private function

        GravitonFermionVertexSpinConnectionOrderedUncontracted.

    The function

        GravitonFermionVertexOrderedUncontracted

    returns the ordered, non-symmetrised sum of these two contributions.

    The public function

        GravitonFermionVertexUncontracted[indexArray, p1, p2, mass]

    returns the complete uncontracted expression symmetrised over full
    graviton-leg permutations.  It leaves Lorentz-index contractions
    explicit.  This form is useful for debugging, checking the tensor
    structure, and inspecting the intermediate expression before FeynCalc
    performs contractions.

    The public function

        GravitonFermionVertex[indexArray, p1, p2, mass]

    returns the contracted form of the same graviton-symmetric vertex.

    The input indexArray is a flattened list of graviton data:

        {rho1, sigma1, k1, ..., rhon, sigman, kn}.

    Here {rhoi, sigmai} are the Lorentz indices of the i-th graviton and
    ki is its incoming momentum.  The fermion momenta p1 and p2 are also
    taken incoming, following the package convention.

    The symmetrisation over external gravitons is performed by permuting
    full graviton triples

        {rhoi, sigmai, ki},

    not by separately permuting Lorentz indices and momenta.

    Internally, the helper TakeLorentzIndices extracts

        {rho1, sigma1, ..., rhon, sigman},

    while TakeMomenta extracts

        {k1, ..., kn}.

    The implementation relies on the tensor generators

        CTensorGeneral      for Sqrt[-g],
        CETensor            for Sqrt[-g] (e^mu)_m
                            and Sqrt[-g] (e^mu)_m (e^nu)_n,
        ETensor             for the lowered vierbein (e_beta)_m.

    Dirac matrices are represented with GAD and Lorentz-vector
    components with FVD, following FeynCalc notation.
*)




(* Resolve sibling dependencies before nested loads change $InputFileName.
   Keep the caller's working directory and context search path unchanged. *)
With[{rulesDirectory = DirectoryName[$InputFileName]},
    Block[{$ContextPath = $ContextPath},
        Scan[
            Needs[#[[1]], FileNameJoin[{rulesDirectory, #[[2]]}]] &,
            {
                {"CTensorGeneral`", "CTensorGeneral.wl"},
                {"CETensor`", "CETensor.wl"},
                {"ETensor`", "ETensor.wl"}
            }
        ]
    ]
];


(* Shared validation is loaded by absolute path without changing Directory[]. *)
With[{validationFile = FileNameJoin[{DirectoryName[$InputFileName], "RuleValidation.wl"}]},
    Block[{$ContextPath = $ContextPath}, Needs["RuleValidation`", validationFile]]
];

BeginPackage[
    "GravitonFermionVertex`",
    {
        "FeynCalc`",
        "CTensorGeneral`",
        "CETensor`",
        "ETensor`"
    }
];


GravitonFermionVertexUncontracted::usage =
"GravitonFermionVertexUncontracted[indexArray, p1, p2, mass] returns the \
uncontracted n-graviton/two-fermion vertex generated by the perturbative \
expansion of the Dirac action in the vierbein formalism.

The input indexArray must have the form \
{rho1, sigma1, k1, ..., rhon, sigman, kn}, where {rhoi, sigmai} are the \
Lorentz indices of the i-th graviton and ki is its incoming momentum.  The \
symbols p1 and p2 denote the incoming fermion momenta, and mass is the \
fermion mass.

The result includes both contributions: the kinetic-plus-mass term containing \
Sqrt[-g] (e^mu)_m and Sqrt[-g], and the spin-connection term containing \
partial_alpha (e_beta)_m and Sqrt[-g] (e^alpha)_a (e^beta)_b.  The function \
symmetrises the expression over full graviton-leg permutations but does not \
apply Contract, so Lorentz-index contractions are left explicit.";


GravitonFermionVertex::usage =
"GravitonFermionVertex[indexArray, p1, p2, mass] returns the contracted \
n-graviton/two-fermion vertex generated by the perturbative expansion of the \
Dirac action in the vierbein formalism.

The input indexArray must have the form \
{rho1, sigma1, k1, ..., rhon, sigman, kn}, where {rhoi, sigmai} are the \
Lorentz indices of the i-th graviton and ki is its incoming momentum.  The \
symbols p1 and p2 denote the incoming fermion momenta, and mass is the \
fermion mass.

The function evaluates the graviton-symmetric uncontracted vertex and then \
applies Contract to perform Lorentz-index contractions.";


(* Keep helpers and memoised definitions local to this rule package. *)

(* Structural failures are returned as values; callers should use FailureQ. *)
GravitonFermionVertexUncontracted::usage = GravitonFermionVertexUncontracted::usage <> " Supported signatures: GravitonFermionVertexUncontracted[indexArray, p1, p2, mass]; argument 1: flat list, block size 3, length 0 to Infinity; argument 2: symbolic expression (not a list or association); argument 3: symbolic expression (not a list or association); argument 4: symbolic expression (not a list or association)." <> " Invalid argument counts, malformed arrays and unsupported parameter ranges return Failure. Existing dependency failures are propagated; check FailureQ before using the result. See Rules/README.md for the argument contract.";
GravitonFermionVertex::usage = GravitonFermionVertex::usage <> " Supported signatures: GravitonFermionVertex[indexArray, p1, p2, mass]; argument 1: flat list, block size 3, length 0 to Infinity; argument 2: symbolic expression (not a list or association); argument 3: symbolic expression (not a list or association); argument 4: symbolic expression (not a list or association)." <> " Invalid argument counts, malformed arrays and unsupported parameter ranges return Failure. Existing dependency failures are propagated; check FailureQ before using the result. See Rules/README.md for the argument contract.";

Begin["`Private`"];


(* ---------------------------------------------------------------------- *)
(* Basic index-array helpers                                              *)
(* ---------------------------------------------------------------------- *)


Clear[TakeLorentzIndices];

(*
    TakeLorentzIndices[indexArray]

    Extracts the Lorentz-index part of the flattened graviton data.

    Input:

        {rho1, sigma1, k1, ..., rhon, sigman, kn}

    Output:

        {rho1, sigma1, ..., rhon, sigman}.
*)

TakeLorentzIndices[indexArray_] :=
    RuleValidation`RuleCall[
        TakeLorentzIndices[indexArray],
        {{1, "Array", 3, 0, Infinity}},
        (
Flatten[RuleValidation`RuleRequire[
        (Take[#, 2] &) /@
            Partition[indexArray, 3]
    ]]
        ), False
    ];



Clear[TakeLorenzIndices];

(*
    Backward-compatible spelling used in older FeynGrav files.
*)

TakeLorenzIndices[indexArray_] :=
    RuleValidation`RuleCall[
        TakeLorenzIndices[indexArray],
        {{1, "Array", 3, 0, Infinity}},
        (
RuleValidation`RuleRequire[TakeLorentzIndices[indexArray]]
        ), False
    ];


Clear[TakeMomenta];

(*
    TakeMomenta[indexArray]

    Extracts the momentum part of the flattened graviton data.

    Input:

        {rho1, sigma1, k1, ..., rhon, sigman, kn}

    Output:

        {k1, ..., kn}.
*)

TakeMomenta[indexArray_] :=
    RuleValidation`RuleCall[
        TakeMomenta[indexArray],
        {{1, "Array", 3, 0, Infinity}},
        (
If[
        indexArray === {},
        {},
        (#[[3]] &) /@
            Partition[indexArray, 3]
    ]
        ), False
    ];


(* ---------------------------------------------------------------------- *)
(* Graviton-leg permutation helpers                                       *)
(* ---------------------------------------------------------------------- *)


Clear[GravitonFermionVertexGravitonLegs];

(*
    GravitonFermionVertexGravitonLegs[indexArray]

    Splits the flattened graviton data

        {rho1, sigma1, k1, ..., rhon, sigman, kn}

    into full graviton legs

        {{rho1, sigma1, k1}, ..., {rhon, sigman, kn}}.

    Full graviton-leg permutations must act on these triples, not on
    Lorentz indices and momenta separately.
*)

GravitonFermionVertexGravitonLegs[indexArray_] :=
    RuleValidation`RuleCall[
        GravitonFermionVertexGravitonLegs[indexArray],
        {{1, "Array", 3, 0, Infinity}},
        (
Partition[indexArray, 3]
        ), False
    ];


Clear[GravitonFermionVertexPermutedIndexArrays];

(*
    GravitonFermionVertexPermutedIndexArrays[indexArray]

    Returns all flattened index arrays obtained by permuting full
    graviton legs.

    Example:

        {rho1, sigma1, k1, rho2, sigma2, k2}

    gives

        {
            {rho1, sigma1, k1, rho2, sigma2, k2},
            {rho2, sigma2, k2, rho1, sigma1, k1}
        }.

    This operation turns an ordered coefficient into the final
    graviton-symmetric vertex.
*)

GravitonFermionVertexPermutedIndexArrays[indexArray_] :=
    RuleValidation`RuleCall[
        GravitonFermionVertexPermutedIndexArrays[indexArray],
        {{1, "Array", 3, 0, Infinity}},
        (
Flatten /@
            Permutations[
                RuleValidation`RuleRequire[GravitonFermionVertexGravitonLegs[indexArray]]
            ]
        ), True
    ];


(* ---------------------------------------------------------------------- *)
(* Ordered kinetic-plus-mass contribution                                 *)
(* ---------------------------------------------------------------------- *)


Clear[GravitonFermionVertexKineticMassOrderedUncontracted];

(*
    GravitonFermionVertexKineticMassOrderedUncontracted[indexArray, p1, p2, mass]

    Ordered, uncontracted contribution from

        Sqrt[-g] (e^mu)_m
            1/2 [bar[psi] gamma^m partial_mu psi
                 - partial_mu bar[psi] gamma^m psi]

    and from

        - mass Sqrt[-g] bar[psi] psi.

    Explicitly, it implements

        I kappa^n [
            1/2 (Sqrt[-g] (e^mu)_m)^{rho1 sigma1 ... rhon sigman}
                gamma^m (p2 - p1)_mu

            - mass (Sqrt[-g])^{rho1 sigma1 ... rhon sigman}
        ].

    This expression is ordered in the graviton legs.  It is not yet
    symmetrised over full graviton-leg permutations.
*)

GravitonFermionVertexKineticMassOrderedUncontracted[indexArray_, p1_, p2_, mass_] :=
    RuleValidation`RuleCall[
        GravitonFermionVertexKineticMassOrderedUncontracted[indexArray, p1, p2, mass],
        {{1, "Array", 3, 0, Infinity}, {2, "Expression"}, {3, "Expression"}, {4, "Expression"}},
        (
Module[{lorentzIndexArray, numberOfGravitons, mu, m},

            lorentzIndexArray = RuleValidation`RuleRequire[TakeLorentzIndices[indexArray]];
            numberOfGravitons = Length[indexArray]/3;

            mu = Unique["mu"];
            m = Unique["m"];

            (
                I Global`\[Kappa]^numberOfGravitons
                (
                    1/2
                    RuleValidation`RuleRequire[CETensor[
                        {mu, m},
                        lorentzIndexArray
                    ]]
                    GAD[m]
                    FVD[p2 - p1, mu]

                    - mass
                    RuleValidation`RuleRequire[CTensorGeneral[
                        {},
                        lorentzIndexArray
                    ]]
                )
            ) // ExpandScalarProduct // Expand // FeynCalcInternal
        ]
        ), True
    ];


(* ---------------------------------------------------------------------- *)
(* Ordered spin-connection contribution                                   *)
(* ---------------------------------------------------------------------- *)


Clear[GravitonFermionVertexSpinConnectionOrderedUncontracted];

(*
    GravitonFermionVertexSpinConnectionOrderedUncontracted[indexArray, p1, p2, mass]

    Ordered, uncontracted contribution from the spin-connection term

        I kappa^n 1/8 Sum[
            (k1 + ... + ks)_alpha
            ((e_beta)_m)^{rho1 sigma1 ... rhos sigmas}
            (Sqrt[-g] (e^alpha)_a (e^beta)_b)
                ^{rho{s+1} sigma{s+1} ... rhon sigman}
            (gamma^a gamma^m gamma^b
             - gamma^b gamma^m gamma^a),
            {s, 1, n}
        ].

    The mass argument is kept only to preserve the same argument pattern
    as the other vertex functions.  It is not used in this contribution.

    This expression is ordered in the graviton legs.  It is not yet
    symmetrised over full graviton-leg permutations.
*)

GravitonFermionVertexSpinConnectionOrderedUncontracted[indexArray_, p1_, p2_, mass_] :=
    RuleValidation`RuleCall[
        GravitonFermionVertexSpinConnectionOrderedUncontracted[indexArray, p1, p2, mass],
        {{1, "Array", 3, 0, Infinity}, {2, "Expression"}, {3, "Expression"}, {4, "Expression"}},
        (
Module[
            {
                lorentzIndexArray,
                momentaArray,
                numberOfGravitons,
                alpha, beta,
                a, b, m
            },

            lorentzIndexArray = RuleValidation`RuleRequire[TakeLorentzIndices[indexArray]];
            momentaArray = RuleValidation`RuleRequire[TakeMomenta[indexArray]];
            numberOfGravitons = Length[indexArray]/3;

            alpha = Unique["alpha"];
            beta = Unique["beta"];

            a = Unique["a"];
            b = Unique["b"];
            m = Unique["m"];

            If[
                numberOfGravitons == 0,

                0,

                (
                    I Global`\[Kappa]^numberOfGravitons
                    (
                        1/8
                        Sum[
                            FVD[
                                Total[RuleValidation`RuleRequire[Take[momentaArray, s]]],
                                alpha
                            ]
                            RuleValidation`RuleRequire[ETensor[
                                {beta, m},
                                Take[lorentzIndexArray, 2 s]
                            ]]
                            RuleValidation`RuleRequire[CETensor[
                                {alpha, a},
                                {beta, b},
                                Drop[lorentzIndexArray, 2 s]
                            ]]
                            (
                                GAD[a, m, b] - GAD[b, m, a]
                            ),
                            {s, 1, numberOfGravitons}
                        ]
                    )
                ) // ExpandScalarProduct // Expand // FeynCalcInternal
            ]
        ]
        ), True
    ];


(* ---------------------------------------------------------------------- *)
(* Ordered full uncontracted vertex                                       *)
(* ---------------------------------------------------------------------- *)


Clear[GravitonFermionVertexOrderedUncontracted];

(*
    GravitonFermionVertexOrderedUncontracted[indexArray, p1, p2, mass]

    Ordered, uncontracted sum of the kinetic-plus-mass contribution and
    the spin-connection contribution.

    This expression is still not symmetrised over full graviton-leg
    permutations.
*)

GravitonFermionVertexOrderedUncontracted[indexArray_, p1_, p2_, mass_] :=
    RuleValidation`RuleCall[
        GravitonFermionVertexOrderedUncontracted[indexArray, p1, p2, mass],
        {{1, "Array", 3, 0, Infinity}, {2, "Expression"}, {3, "Expression"}, {4, "Expression"}},
        (
(
            RuleValidation`RuleRequire[GravitonFermionVertexKineticMassOrderedUncontracted[
                indexArray,
                p1,
                p2,
                mass
            ]]

            +

            RuleValidation`RuleRequire[GravitonFermionVertexSpinConnectionOrderedUncontracted[
                indexArray,
                p1,
                p2,
                mass
            ]]
        ) // ExpandScalarProduct // Expand // FeynCalcInternal
        ), True
    ];


(* ---------------------------------------------------------------------- *)
(* Symmetrised full uncontracted vertex                                   *)
(* ---------------------------------------------------------------------- *)


Clear[GravitonFermionVertexUncontracted];

(*
    GravitonFermionVertexUncontracted[indexArray, p1, p2, mass]

    Returns the full uncontracted graviton-fermion vertex symmetrised over
    all full graviton-leg permutations.

    The symmetrisation is a sum over all permutations of the triples

        {rhoi, sigmai, ki}.

    No Contract is applied here.
*)

GravitonFermionVertexUncontracted[indexArray_, p1_, p2_, mass_] :=
    RuleValidation`RuleCall[
        GravitonFermionVertexUncontracted[indexArray, p1, p2, mass],
        {{1, "Array", 3, 0, Infinity}, {2, "Expression"}, {3, "Expression"}, {4, "Expression"}},
        (
(
            Total[RuleValidation`RuleRequire[
                RuleValidation`RuleRequire[Map[
                    RuleValidation`RuleRequire[GravitonFermionVertexOrderedUncontracted[
                        #,
                        p1,
                        p2,
                        mass
                    ]] &,
                    RuleValidation`RuleRequire[GravitonFermionVertexPermutedIndexArrays[indexArray]]
                ]]
            ]]
        ) // ExpandScalarProduct // Expand // FeynCalcInternal
        ), True
    ];


(* ---------------------------------------------------------------------- *)
(* Symmetrised full contracted vertex                                     *)
(* ---------------------------------------------------------------------- *)


Clear[GravitonFermionVertex];

(*
    GravitonFermionVertex[indexArray, p1, p2, mass]

    Returns the full contracted graviton-fermion vertex symmetrised over
    all full graviton-leg permutations.

    This is the public function intended for ordinary use.
*)

GravitonFermionVertex[indexArray_, p1_, p2_, mass_] :=
    RuleValidation`RuleCall[
        GravitonFermionVertex[indexArray, p1, p2, mass],
        {{1, "Array", 3, 0, Infinity}, {2, "Expression"}, {3, "Expression"}, {4, "Expression"}},
        (
(
            RuleValidation`RuleRequire[GravitonFermionVertexUncontracted[
                indexArray,
                p1,
                p2,
                mass
            ]]
            // Contract
            // ExpandScalarProduct
            // Expand
            // FeynCalcInternal
        )
        ), True
    ];




(* Unsupported arities fail before any calculation. *)
GravitonFermionVertex[arguments___] /; !MemberQ[{4}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[GravitonFermionVertex] <> SymbolName[GravitonFermionVertex], {arguments}, {4}];

GravitonFermionVertexGravitonLegs[arguments___] /; !MemberQ[{1}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[GravitonFermionVertexGravitonLegs] <> SymbolName[GravitonFermionVertexGravitonLegs], {arguments}, {1}];

GravitonFermionVertexKineticMassOrderedUncontracted[arguments___] /; !MemberQ[{4}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[GravitonFermionVertexKineticMassOrderedUncontracted] <> SymbolName[GravitonFermionVertexKineticMassOrderedUncontracted], {arguments}, {4}];

GravitonFermionVertexOrderedUncontracted[arguments___] /; !MemberQ[{4}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[GravitonFermionVertexOrderedUncontracted] <> SymbolName[GravitonFermionVertexOrderedUncontracted], {arguments}, {4}];

GravitonFermionVertexPermutedIndexArrays[arguments___] /; !MemberQ[{1}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[GravitonFermionVertexPermutedIndexArrays] <> SymbolName[GravitonFermionVertexPermutedIndexArrays], {arguments}, {1}];

GravitonFermionVertexSpinConnectionOrderedUncontracted[arguments___] /; !MemberQ[{4}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[GravitonFermionVertexSpinConnectionOrderedUncontracted] <> SymbolName[GravitonFermionVertexSpinConnectionOrderedUncontracted], {arguments}, {4}];

GravitonFermionVertexUncontracted[arguments___] /; !MemberQ[{4}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[GravitonFermionVertexUncontracted] <> SymbolName[GravitonFermionVertexUncontracted], {arguments}, {4}];

TakeLorentzIndices[arguments___] /; !MemberQ[{1}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[TakeLorentzIndices] <> SymbolName[TakeLorentzIndices], {arguments}, {1}];

TakeLorenzIndices[arguments___] /; !MemberQ[{1}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[TakeLorenzIndices] <> SymbolName[TakeLorenzIndices], {arguments}, {1}];

TakeMomenta[arguments___] /; !MemberQ[{1}, Length[{arguments}]] :=
    RuleValidation`RuleArityFailure[Context[TakeMomenta] <> SymbolName[TakeMomenta], {arguments}, {1}];

End[];


EndPackage[];
