(* ::Package:: *)

BeginPackage["Nieuwenhuizen`",{"FeynCalc`"}];


GaugeProjector::usage = "GaugeProjector[\[Mu],\[Nu],p]. The standard gauge projector \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)(p) = \!\(\*SubscriptBox[\(\[Eta]\), \(\[Mu]\[Nu]\)]\)-\!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\)."
GaugeProjectorBar::usage = "GaugeProjector[\[Mu],\[Nu],p]. The standard gauge projector \!\(\*SubscriptBox[OverscriptBox[\(\[Theta]\), \(_\)], \(\[Mu]\[Nu]\)]\)(p) = \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\)."


NieuwenhuizenOperator1::usage = "NieuwenhuizenOperator1[\[Mu],\[Nu],\[Alpha],\[Beta],p]. Nieuwenhuizen operator (\!\(\*SuperscriptBox[\(P\), \(1\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\) = \!\(\*FractionBox[\(1\), \(2\)]\)(\!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Alpha]\)]\)\!\(\*SubscriptBox[\(\[Omega]\), \(\[Nu]\[Beta]\)]\)+\!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Beta]\)]\)\!\(\*SubscriptBox[\(\[Omega]\), \(\[Nu]\[Alpha]\)]\)+\!\(\*SubscriptBox[\(\[Theta]\), \(\[Nu]\[Alpha]\)]\)\!\(\*SubscriptBox[\(\[Omega]\), \(\[Mu]\[Beta]\)]\)+\!\(\*SubscriptBox[\(\[Theta]\), \(\[Nu]\[Beta]\)]\)\!\(\*SubscriptBox[\(\[Omega]\), \(\[Mu]\[Alpha]\)]\)). Here \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)=\!\(\*SubscriptBox[\(\[Eta]\), \(\[Mu]\[Nu]\)]\) - \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\) are the standard gauge projectors and \!\(\*SubscriptBox[\(\[Omega]\), \(\[Mu]\[Nu]\)]\) = \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\) are projectors orthogonal to \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)."
NieuwenhuizenOperator2::usage = "NieuwenhuizenOperator2[\[Mu],\[Nu],\[Alpha],\[Beta],p]. Nieuwenhuizen operator (\!\(\*SuperscriptBox[\(P\), \(2\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\) = \!\(\*FractionBox[\(1\), \(2\)]\)(\!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Alpha]\)]\)\!\(\*SubscriptBox[\(\[Theta]\), \(\[Nu]\[Beta]\)]\)+\!\(\*SubscriptBox[\(\[Theta]\), \(\[Nu]\[Beta]\)]\)\!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Alpha]\)]\))-\!\(\*FractionBox[\(1\), \(3\)]\)\!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)\!\(\*SubscriptBox[\(\[Theta]\), \(\[Alpha]\[Beta]\)]\). Here \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)=\!\(\*SubscriptBox[\(\[Eta]\), \(\[Mu]\[Nu]\)]\) - \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\) are the standard gauge projectors."
NieuwenhuizenOperator0::usage = "NieuwenhuizenOperator0[\[Mu],\[Nu],\[Alpha],\[Beta],p]. Nieuwenhuizen operator (\!\(\*SuperscriptBox[\(P\), \(0\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\) = \!\(\*FractionBox[\(1\), \(3\)]\)\!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)\!\(\*SubscriptBox[\(\[Theta]\), \(\[Alpha]\[Beta]\)]\). Here \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)=\!\(\*SubscriptBox[\(\[Eta]\), \(\[Mu]\[Nu]\)]\) - \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\) are the standard gauge projectors."
NieuwenhuizenOperator0Bar::usage = "NieuwenhuizenOperator0Bar[\[Mu],\[Nu],\[Alpha],\[Beta],p]. Nieuwenhuizen operator (\!\(\*OverscriptBox[SuperscriptBox[\(P\), \(0\)], \(_\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\) =\!\(\*SubscriptBox[\(\[Omega]\), \(\[Mu]\[Nu]\)]\)\!\(\*SubscriptBox[\(\[Omega]\), \(\[Alpha]\[Beta]\)]\). Here \!\(\*SubscriptBox[\(\[Omega]\), \(\[Mu]\[Nu]\)]\) = \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\) are projectors orthogonal to the standard gauge projector \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)=\!\(\*SubscriptBox[\(\[Eta]\), \(\[Mu]\[Nu]\)]\) - \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\)."
NieuwenhuizenOperator0BarBar::usage = "NieuwenhuizenOperator0BarBar[\[Mu],\[Nu],\[Alpha],\[Beta],p]. Nieuwenhuizen operator (\!\(\*OverscriptBox[OverscriptBox[SuperscriptBox[\(P\), \(0\)], \(_\)], \(_\)]\)\!\(\*SubscriptBox[\()\), \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\) = \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)\!\(\*SubscriptBox[\(\[Omega]\), \(\[Alpha]\[Beta]\)]\)+\!\(\*SubscriptBox[\(\[Theta]\), \(\[Alpha]\[Beta]\)]\)\!\(\*SubscriptBox[\(\[Omega]\), \(\[Mu]\[Nu]\)]\). Here \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)=\!\(\*SubscriptBox[\(\[Eta]\), \(\[Mu]\[Nu]\)]\) - \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\) are the standard gauge projectors and \!\(\*SubscriptBox[\(\[Omega]\), \(\[Mu]\[Nu]\)]\) = \!\(\*SubscriptBox[\(p\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(p\), \(\[Nu]\)]\)/\!\(\*SuperscriptBox[\(p\), \(2\)]\) are projectors orthogonal to \!\(\*SubscriptBox[\(\[Theta]\), \(\[Mu]\[Nu]\)]\)."
NieuwenhuizenOperator::usage = "NieuwenhuizenOperator[\!\(\*SubscriptBox[\(z\), \(1\)]\),\!\(\*SubscriptBox[\(z\), \(2\)]\),\!\(\*SubscriptBox[\(z\), \(0\)]\),\!\(\*SubscriptBox[\(z\), \(b\)]\),\!\(\*SubscriptBox[\(z\), \(bb\)]\),\[Mu],\[Nu],\[Alpha],\[Beta],p]. A linear combination of Nieuwenhuizen operators: \!\(\*SubscriptBox[\(z\), \(1\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(P\), \(1\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(2\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(P\), \(2\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(0\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(P\), \(0\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(b\)]\)\!\(\*SubscriptBox[SuperscriptBox[OverscriptBox[\(P\), \(_\)], \(0\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(bb\)]\)\!\(\*SubscriptBox[SuperscriptBox[OverscriptBox[\(P\), OverscriptBox[\(_\), \(_\)]], \(0\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)."
NieuwenhuizenOperatorInverse::usage = "NieuwenhuizenOperatorInverse[\!\(\*SubscriptBox[\(z\), \(1\)]\),\!\(\*SubscriptBox[\(z\), \(2\)]\),\!\(\*SubscriptBox[\(z\), \(0\)]\),\!\(\*SubscriptBox[\(z\), \(b\)]\),\!\(\*SubscriptBox[\(z\), \(bb\)]\),\[Mu],\[Nu],\[Alpha],\[Beta],p]. A linear combination of Nieuwenhuizen operators which is inverse for \!\(\*SubscriptBox[\(z\), \(1\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(P\), \(1\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(2\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(P\), \(2\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(0\)]\)\!\(\*SubscriptBox[SuperscriptBox[\(P\), \(0\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(b\)]\)\!\(\*SubscriptBox[SuperscriptBox[OverscriptBox[\(P\), \(_\)], \(0\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)+\!\(\*SubscriptBox[\(z\), \(bb\)]\)\!\(\*SubscriptBox[SuperscriptBox[OverscriptBox[\(P\), OverscriptBox[\(_\), \(_\)]], \(0\)], \(\[Mu]\[Nu]\[Alpha]\[Beta]\)]\)(p)."


NieuwenhuizenOperatorExpansion::usage = "NieuwenhuizenOperatorExpansion[T,\[Mu],\[Nu],\[Alpha],\[Beta],p]. The function takes a tensor T with Lorentz indices {\[Mu],\[Nu],\[Alpha],\[Beta]} that may depend on the momentum p. The function expands the tensor in Nieuwenhuizen operators and returns a set of coordinates {\!\(\*SubscriptBox[\(z\), \(1\)]\),\!\(\*SubscriptBox[\(z\), \(2\)]\),\!\(\*SubscriptBox[\(z\), \(0\)]\),\!\(\*SubscriptBox[OverscriptBox[\(z\), \(_\)], \(0\)]\),\!\(\*SubscriptBox[OverscriptBox[\(z\), OverscriptBox[\(_\), \(_\)]], \(0\)]\)} which can be used with NieuwenhuizenOperator.";


Begin["Private`"];


GaugeProjector[m_,n_,p_] = Pair[LorentzIndex[m,D],LorentzIndex[n,D]]-FeynAmpDenominator[PropagatorDenominator[Momentum[p,D],0]] Pair[LorentzIndex[m,D],Momentum[p,D]] Pair[LorentzIndex[n,D],Momentum[p,D]];
GaugeProjectorBar[m_,n_,p_] = FeynAmpDenominator[PropagatorDenominator[Momentum[p,D],0]] Pair[LorentzIndex[m,D],Momentum[p,D]] Pair[LorentzIndex[n,D],Momentum[p,D]];


NieuwenhuizenOperator1 = {\[Mu],\[Nu],\[Alpha],\[Beta],k}|->1/2 (GaugeProjector[\[Mu],\[Alpha],k]GaugeProjectorBar[\[Nu],\[Beta],k] + GaugeProjector[\[Mu],\[Beta],k]GaugeProjectorBar[\[Nu],\[Alpha],k] + GaugeProjector[\[Nu],\[Alpha],k]GaugeProjectorBar[\[Mu],\[Beta],k] + GaugeProjector[\[Nu],\[Beta],k]GaugeProjectorBar[\[Mu],\[Alpha],k]) //FeynAmpDenominatorCombine;
NieuwenhuizenOperator2 = {\[Mu],\[Nu],\[Alpha],\[Beta],k}|->1/2 (GaugeProjector[\[Mu],\[Alpha],k]GaugeProjector[\[Nu],\[Beta],k] + GaugeProjector[\[Mu],\[Beta],k]GaugeProjector[\[Nu],\[Alpha],k]) - 1/3 GaugeProjector[\[Mu],\[Nu],k]GaugeProjector[\[Alpha],\[Beta],k] //FeynAmpDenominatorCombine;
NieuwenhuizenOperator0 = {\[Mu],\[Nu],\[Alpha],\[Beta],k}|->1/3 GaugeProjector[\[Mu],\[Nu],k]GaugeProjector[\[Alpha],\[Beta],k] //FeynAmpDenominatorCombine;
NieuwenhuizenOperator0Bar = {\[Mu],\[Nu],\[Alpha],\[Beta],k}|-> GaugeProjectorBar[\[Mu],\[Nu],k]GaugeProjectorBar[\[Alpha],\[Beta],k] //FeynAmpDenominatorCombine;
NieuwenhuizenOperator0BarBar = {\[Mu],\[Nu],\[Alpha],\[Beta],k}|->GaugeProjector[\[Mu],\[Nu],k]GaugeProjectorBar[\[Alpha],\[Beta],k] + GaugeProjectorBar[\[Mu],\[Nu],k]GaugeProjector[\[Alpha],\[Beta],k] //FeynAmpDenominatorCombine;


NieuwenhuizenOperator = {z1,z2,z0,z0b,z0bb,\[Mu],\[Nu],\[Alpha],\[Beta],k}|->z1 NieuwenhuizenOperator1[\[Mu],\[Nu],\[Alpha],\[Beta],k]+z2 NieuwenhuizenOperator2[\[Mu],\[Nu],\[Alpha],\[Beta],k]+z0 NieuwenhuizenOperator0[\[Mu],\[Nu],\[Alpha],\[Beta],k]+z0b NieuwenhuizenOperator0Bar[\[Mu],\[Nu],\[Alpha],\[Beta],k]+z0bb NieuwenhuizenOperator0BarBar[\[Mu],\[Nu],\[Alpha],\[Beta],k]//FeynAmpDenominatorCombine;
NieuwenhuizenOperatorInverse = {z1,z2,z0,z0b,z0bb,\[Mu],\[Nu],\[Alpha],\[Beta],k}|->1/z1 NieuwenhuizenOperator1[\[Mu],\[Nu],\[Alpha],\[Beta],k]+1/z2 NieuwenhuizenOperator2[\[Mu],\[Nu],\[Alpha],\[Beta],k]+1/z2 (((D-4)(z0 z0b -3 z0bb^2)-(D-7)z2 z0b)/((D-1)(z0 z0b -3 z0bb^2)-(D-4)z2 z0b)) NieuwenhuizenOperator0[\[Mu],\[Nu],\[Alpha],\[Beta],k]+((D-1)z0-(D-4)z2)/((D-1)(z0 z0b -3 z0bb^2)-(D-4)z2 z0b) NieuwenhuizenOperator0Bar[\[Mu],\[Nu],\[Alpha],\[Beta],k]-(3 z0bb)/((D-1)(z0 z0b -3 z0bb^2)-(D-4)z2 z0b) NieuwenhuizenOperator0BarBar[\[Mu],\[Nu],\[Alpha],\[Beta],k]//FeynAmpDenominatorCombine;


NieuwenhuizenSymmetryCheck[T_,m_,n_,a_,b_,p_] := TrueQ[Calc[T-(T/.{m->n,n->m})]==0]&&TrueQ[Calc[T-(T/.{a->b,b->a})]==0]&&TrueQ[Calc[T-(T/.{m->a,n->b,a->m,b->n})]==0];


NieuwenhuizenOperatorExpansion[T_,m_,n_,a_,b_,p_] := If[ NieuwenhuizenSymmetryCheck[T,m,n,a,b,p], SolveValues[  #==0&/@Coefficient[ Calc[FeynAmpDenominatorExplicit[T-NieuwenhuizenOperator[z1,z2,z0,zb,zbb,m,n,a,b,p]]] ,Calc[{MTD[m,n]MTD[a,b],MTD[m,a]MTD[n,b],MTD[m,n]FVD[p,a]FVD[p,b],MTD[m,a]FVD[p,n]FVD[p,b],FVD[p,m]FVD[p,n]FVD[p,a]FVD[p,b]}]]  ,{z1,z2,z0,zb,zbb} ][[1]]  , Print["The tensor does not admits symmetries required to be expanded by the Nieuwenhuizen operators!"] ] ; 


End[];


EndPackage[];
